### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by ad-si** [JakeWheat/simple-sql-parser#16]
How about releasing 0.5.0? Looks like already quite a few things have already been implemented since 0.4.4. Or is there still anything important missing? I'd be happy to help if that's the case!

**Comment by JakeWheat** [comment]
Hi,
(I'm a little busy at the moment.) There's a lot of new features added that are partly finished. If you want to do a review on how these would look in a release, that would be good. Anything else you can do to help get a release would be great. I can help too if you find anything that really needs doing. Since it's been so long, it would be good just to smooth off any rough edges instead of trying to really complete the new features, then launch it like that, a lot better than nothing.
Thanks.

**Comment by ad-si** [comment]
No problem. I'm busy as well 😅.

I've been using it in a language server which checks SQL code. The master head has been working well for me so far. I'll pick up the project again the coming weeks and let you know if I get any more insights!

**Comment by JakeWheat** [comment]
I finally got round to releasing a 0.5.0 with the basic other DML, DDL, etc. syntax support. Thanks for the suggestion.
