### ISSUE TITLE
Support of SQLSERVER CONVERT function

### ISSUE THREAD

**Issue by bartoszw** [JakeWheat/simple-sql-parser#35]
Hi,

I've encountered following issue:
Input looks like 
`convert(1,year(EFLHurtF01.dbo.FFINPFH.DTZAWC)),`
the error message is 

> testSqlParser: :128:13:
> convert(char,datepart(qq, 
>             ^
> (line 128, column 13):
> unexpected Symbol ","
> expecting scalar expression
> CallStack (from HasCallStack):
>   error, called at testSqlParser.hs:77:13 in main:Main

comming from difference beetwen function

`> convert :: Parser ScalarExpr`
`> convert = specialOpK "convert" SOKMandatory [("using", True)]`

and [MS syntax definiton of convert](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15).
which says
`-- CONVERT Syntax:  
CONVERT ( data_type [ ( length ) ] , expression [ , style ] )  `

If you give me a hint which direction this could be solved, I'd make an effort and see if I manage to fix it.
Or, if I'm mixing something, please let me know, maybe the issue is somewhere else and I'm just overlooking it.

I'm not mentioning version of GHC or OS, it seems to me to be irrelevant in this case.

Best regards,
Bartosz Wójcik

**Comment by JakeWheat** [comment]
I think a good solution here is to add flags to the dialect for each of these weird Ansi SQL syntax functions, to enable/disable it. When the flag for a special function is disabled, that function will parse as a regular function instead of the special case.

To start, you could add a dialect flag which disables the special parsing of convert only, and use this in the MSSQL dialect.

**Comment by JakeWheat** [comment]
Fixed in #36, thanks.
